version: "3.3"
services:
  csvserver:
    image: infracloudio/csvserver
    container_name: csvserver
    volumes:
      - ./inputdata:/csvserver/inputdata
    ports:
      - 9393:9300
    env_file:
      - csvserver.env

  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - csvserver

